version: '3.7'
services:
  nginx:
    container_name: nginx-container
    image: luvneries/web-server
    build:
      context: ./nginx-server/
      dockerfile: Dockerfile
    volumes:
      - ./nginx-server/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx-server/index.html:/etc/nginx/html/index.html
    networks:
      - my-web-network
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - flask-server

  flask-server:
    container_name: flask-container
    image: luvneries/api-server
    build:
      context: ./flask-server/
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./flask-server/:/app
    depends_on:
      - redis-server
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    networks:
      - my-web-network

  redis-server:
    container_name: redis-container
    image: redis
    networks:
      - my-web-network

networks:
  my-web-network: