version: '3.6'
services:
  nginx:
    container_name: nginx-container
    image: luvneries/web-server
    build:
      context: ./web-server/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./web-server/nginx/:/etc/nginx/conf.d/
    networks:
      - my-web-network
    ports:
      - 80:80
    depends_on:
      - flask-server

  redis-server:
    container_name: redis-container
    image: redis
    networks:
      - my-web-network

  flask-server:
    container_name: flask-container
    image: luvneries/api-server
    build:
      context: ./api-server/
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - ./api-server/:/app
    depends_on:
      - redis-server
    environment:
#      - FLASK_APP=/app/main.py
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    #command: flask run --host=0.0.0.0
    #command: gunicorn -w 4 --bind :3000 wsgi:app
    networks:
      - my-web-network

networks:
  my-web-network: