apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: aimlcode-tls
spec:
  secretName: aimlcode-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aimlcode.com
  dnsNames:
    - aimlcode.com
    - www.aimlcode.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - aimlcode.com
          - www.aimlcode.com

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'luvneries@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}