apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: aimlcode-tls
spec:
  secretName: aimlcode-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aimlcode.com
  dnsNames:
    - aimlcode.com
    - www.aimlcode.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - aimlcode.com
          - www.aimlcode.com

